---
# NOTE this has bug with Ansible 2.1.1.0
# https://github.com/ansible/ansible/issues/16865

- name: Configure apt-cacher-ng
  raw: "echo 'Acquire::http::Proxy \"{{ host_preparation_apt_cacher_ng }}\";' >
      /etc/apt/apt.conf.d/11proxy"
  become: true
  delegate_to: "{{ os_volumes_loop.name }}"
  when: host_preparation_apt_cacher_ng is defined

- name: Configure APT compression-types
  raw: "echo 'Acquire::CompressionTypes::Order:: \"{{ host_preparation_apt_compression_types }}\";' >
      /etc/apt/apt.conf.d/12compression-types"
  become: true
  delegate_to: "{{ os_volumes_loop.name }}"
  when: host_preparation_apt_compression_types is defined

- name: Change deb source to archive.ubuntu.com
  become: true
  raw: "sed -i s#http://.*.archive.ubuntu.com#http://archive.ubuntu.com#g /etc/apt/sources.list"
  become: true
  delegate_to: "{{ os_volumes_loop.name }}"

- name: Install Python 2
  raw: "python --version || apt update && apt install -y python"
  become: true
  delegate_to: "{{ os_volumes_loop.name }}"

- name: Format volume
  filesystem:
    fstype: "{{ os_instance.volumes[item.name.split('_')[-1]].fstype | default('ext4') }}"
    dev: "{{ item.attachments[0].device }}"
  when: item.attachments[0].device != '/dev/vda'
  with_items: "{{ os_volumes_loop.volumes }}"
  become: true
  delegate_to: "{{ os_volumes_loop.name }}"

- name: Mount volume
  mount:
    name: "{{ os_instance.volumes[item.name.split('_')[-1]].path }}"
    src: "{{ item.attachments[0].device }}"
    fstype: "{{ os_instance.volumes[item.name.split('_')[-1]].fstype | default('ext4') }}"
    state: mounted
  when: item.attachments[0].device != '/dev/vda'
  with_items: "{{ os_volumes_loop.volumes }}"
  become: true
  delegate_to: "{{ os_volumes_loop.name }}"
